[package]
name = "qmk-sys"
version = "0.1.0"
authors = ["Daniel Prilik <danielprilik@gmail.com>"]
edition = "2018"

[dependencies]

[build-dependencies]
bindgen = "0.51"

[lib]
test = false
bench = false
